include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-zeroclaw
PKG_VERSION:=0.1.0
PKG_RELEASE:=1

PKG_MAINTAINER:=gcy529 <your-email@example.com>
PKG_LICENSE:=MIT

LUCI_TITLE:=LuCI support for ZeroClaw
LUCI_DEPENDS:=+zeroclaw +luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
